name: test
on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: checkout
        uses: actions/checkout@v2

      - name: download modules
        run: go mod download

      - name: test
        run: go test ./...
